#!/usr/bin/env bash
#Displays numbers from 1 to 20

i=1
while ((i<=20))
do
	case $i in
	5)
		echo "bad luck from China";;
	10)
		echo "bad luck from Japan";;
	18)
		echo "bad luck from Italy";;
	esac
	echo $i
	((i++))
done
